version: "3"
services:
  web:
    build: .
    volumes:
      - "./:/app"
    command: npm start
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_DB_NAME=my-transit
      - MONGO_URL=mongodb://localhost
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:4000"
    networks:
      - webnet
  mongo:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
networks:
  webnet:
volumes:
  mongo-data:
