version: "3"
services:
  web:
    build: .
    volumes:
      - "./:/app"
    command: yarn start
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      - MONGO_DB_NAME=my-transit
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - webnet
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo:4.0
    volumes:
      - "mongo:/data/db"
    networks:
      - webnet
    ports:
      - "27017:27017"
    expose:
      - "27017"
networks:
  webnet:
volumes:
  mongo:
