version: "3"
services:
  web:
    image: cantsnuffthedrewster/my-transit-app:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet:
